channels:
- anaconda
- pytorch
- conda-forge
- menpo
dependencies:
- python=3.6.13
- pip>=21.0,<22
- pytorch==1.10.0
- torchaudio==0.10.0
- torchprofile==0.0.4
- torchvision==0.11.1
- cudatoolkit=11.3
- pip:
  - --find-links https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
  - certifi==2021.5.30
  - dataclasses==0.8
  - einops==0.4.1
  - entrypoints==0.3
  - jedi==0.17.0
  - lmdb==1.2.1
  - numpy==1.19.5
  - Pillow==8.4.0
  - protobuf==4.21.0
  - pyarrow==5.0.0
  - PyYAML==6.0
  - tensorboardX==2.4
  - timm==0.4.12
  - typing_extensions==4.1.1
  - yacs==0.1.8
  - wget
  - matplotlib>=3.3,<3.4
  - tqdm>=4.59,<4.60
name: fpc